name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            os_name: linux
            arch: x86_64
            executable: mono
            ext: ""

          - runner: windows-latest
            os_name: windows
            arch: x86_64
            executable: mono.exe
            ext: ".exe"

          - runner: macos-latest
            os_name: macos
            arch: arm64
            executable: mono
            ext: ""

    runs-on: ${{matrix.runner}}

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v5

        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable

        - name: Cache Rust build
          uses: Swatinem/rust-cache@v2

        - name: Build Release
          run: cargo build --release

        - name: Rename Binary
          shell: bash
          run: |
            mv "target/release/${{ matrix.executable }}" \
               "target/release/monochromium-${{ github.ref_name }}-${{ matrix.os_name }}-${{ matrix.arch }}${{ matrix.ext }}"

        - name: Upload Binary Artifact
          uses: actions/upload-artifact@v4
          with:
            name: monochromium-${{ matrix.os_name }}-${{ matrix.arch }}
            path: target/release/monochromium-${{ github.ref_name }}-${{ matrix.os_name }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Generate Checksums
        run: sha256sum artifacts/* > artifacts/SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
